CREATE TABLE v1(id int, embedding vector(3));
INSERT INTO v1 VALUES(1, STRING_TO_VECTOR('[1,2,3]'));
INSERT INTO v1 VALUES(2, STRING_TO_VECTOR('[4,5,6]'));
INSERT INTO v1 VALUES(3, STRING_TO_VECTOR('[1.5,-2,3.25]'));
INSERT INTO v1 VALUES(4, STRING_TO_VECTOR('[7,8,9]'));
INSERT INTO v1 VALUES(5, STRING_TO_VECTOR('[2,2,2]'));
INSERT INTO v1 VALUES(6, STRING_TO_VECTOR('[10,10,10]'));
INSERT INTO v1 VALUES(7, STRING_TO_VECTOR('[0,0,0]'));
INSERT INTO v1 VALUES(8, STRING_TO_VECTOR('[3,3,3]'));
INSERT INTO v1 VALUES(9, STRING_TO_VECTOR('[9,1,5]'));
INSERT INTO v1 VALUES(10, STRING_TO_VECTOR('[1,1,1]'));
INSERT INTO v1 VALUES(11, STRING_TO_VECTOR('[5,5,5]'));
INSERT INTO v1 VALUES(12, STRING_TO_VECTOR('[8,2,4]'));
INSERT INTO v1 VALUES(13, STRING_TO_VECTOR('[6,6,6]'));
INSERT INTO v1 VALUES(14, STRING_TO_VECTOR('[0.5,0.5,0.5]'));
INSERT INTO v1 VALUES(15, STRING_TO_VECTOR('[3,1,4]'));

CREATE VECTOR INDEX idx1 ON v1(embedding) WITH (lists=3, probes=2);

SELECT * FROM v1;
SELECT VECTOR_TO_STRING(embedding) FROM v1;
SELECT id, DISTANCE(embedding, STRING_TO_VECTOR('[1,2,3]'), 'EUCLIDEAN') AS dis FROM v1 ORDER BY dis LIMIT 5;
EXPLAIN SELECT * FROM v1 ORDER BY DISTANCE(embedding, STRING_TO_VECTOR('[1,2,3]'), 'L2_DISTANCE') LIMIT 5;

EXIT;
