CREATE TABLE v1(id int, embedding vector(3));
INSERT INTO v1 VALUES(1, STRING_TO_VECTOR('[1,2,3]'));
INSERT INTO v1 VALUES(2, STRING_TO_VECTOR('[4,5,6]'));
INSERT INTO v1 VALUES(3, STRING_TO_VECTOR('[1.5,-2,3.25]'));
INSERT INTO v1 VALUES(4, STRING_TO_VECTOR('[7,8,9]'));
INSERT INTO v1 VALUES(5, STRING_TO_VECTOR('[2,2,2]'));

CREATE VECTOR INDEX idx1 ON v1(embedding) WITH (lists=2, probes=1);
CREATE VECTOR INDEX idx_bad ON v1(embedding) WITH (lists=0, probes=2);

SELECT * FROM v1;
SELECT VECTOR_TO_STRING(embedding) FROM v1;
SELECT id, DISTANCE(embedding, STRING_TO_VECTOR('[0,0,0]'), 'EUCLIDEAN') FROM v1;

EXIT;